[package]
name = "liischte"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4.40"
anyhow = "*"

tokio = { version = "1.44.1", features = ["rt-multi-thread", "macros", "net", "io-util", "fs"] }
tokio-stream = { version = "0.1.17", features = ["fs"] }
futures = { version = "0.3.31" }
futures-util = "0.3"

# we use cosmic's iced fork
iced = { git = "https://github.com/pop-os/iced", features = ["advanced", "tokio", "winit", "wayland", "multi-window"] }
iced_winit = { git = "https://github.com/pop-os/iced", features = ["wayland", "multi-window"], default-features = false }

log = "0.4.27"
env_logger = "0.11.7"

serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"

# battery integration
tokio-udev = "0.9"

# stuff used for abstraction
downcast = "0.11.0"
dyn-clone = "1.0.19"
async-trait = "0.1.88"
